#!/usr/bin/env ruby

$LOAD_PATH.unshift('lib')

require 'client_loader'

if ARGV.length != 1
  print 'Invalid parameters. Use: "./scan data/customers.jsons"', "\n"
  exit(1)
end

close_clients = ClientLoader.filter(ARGV[0]) do |client|
  DistanceFromDublin.to(client.location) < 100
end

print close_clients.sort_by(&:id).join("\n"), "\n"
